doc-warnings: yes
test-warnings: yes
strictness: medium
max-line-length: 160
requirements:
    - install-requirements
    - test-requirements
ignore-paths:
    - misc
    - jasmin/vendor
ignore-patterns:
    - (^|/)test(/|$)